#ifndef SPU_MEMORYALLOCATOR_SHARED_H_
#define SPU_MEMORYALLOCATOR_SHARED_H_

#define PACKAGE_SPU_MEMORY_SETUP 20
#define PACKAGE_SPU_MEMORY_MALLOC_REQUEST 21
#define PACKAGE_SPU_MEMORY_MALLOC_RESPONSE 22
#define PACKAGE_SPU_MEMORY_FREE 23

/*#define ACTIVATE_DMA_GET_TRANSFER 1999
#define ACTIVATE_DMA_PUT_TRANSFER 1998*/

#endif /*SPU_MEMORYALLOCATOR_SHARED_H_*/
