#ifndef COMMSTIME_GUIDS_H_
#define COMMSTIME_GUIDS_H_

#define PROCESS_COUNTER_GUID 100
#define BARRIER_GUID 101
#define COMPLETION_LOCK 102
#define DELTA_CHANNEL 103

#define CHANNEL_START_GUID 1000

#define REPETITIONS 100000

#endif /* COMMSTIME_GUIDS_H_ */
