#ifndef SPU_MEMORYALLOCATOR_SHARED_H_
#define SPU_MEMORYALLOCATOR_SHARED_H_

#define PACKAGE_SPU_MEMORY_SETUP 20
#define PACKAGE_SPU_MEMORY_MALLOC 21
#define PACKAGE_SPU_MEMORY_FREE 22

#endif /*SPU_MEMORYALLOCATOR_SHARED_H_*/
