#ifndef GUIDS_H_
#define GUIDS_H_

#define ETTAL 1
#define LARGE_ITEM 2
#define SPUITEM 3
#define LOCK_ITEM_PPU 4
#define LOCK_ITEM_SPU 5
#define LARGE_SEQUENCE 100
#define SMALL_SEQUENCE (LARGE_SEQUENCE + SEQUENCE_COUNT + 1)

#define SPU_FIBERS 0

#define SEQUENCE_COUNT 10000
#define SMALL_SEQUENCE_COUNT 1000000

#endif /*GUIDS_H_*/
